before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

brews:
  -
    name: tk
    tap:
      owner: tkhq
      name: homebrew-tap
      branch: main

    download_strategy: CurlDownloadStrategy

    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    description: "Turnkey CLI"
    license: "Apache License 2.0"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
